<?php

use app\core\Database;

require_once __DIR__ . '../../../config/bootstrap.php';
$pdo = Database::getConnection();

// Tickets de ejemplo
$tickets = [
  [
    'title' => 'Error en login',
    'description' => 'No se puede iniciar sesión con usuarios existentes.',
    'status' => 'new',
    'priority' => 'high',
    'category' => 'bug',
    'created_by' => 1,
    'assigned_to' => 2,
    'created_at' => '2025-02-24 13:15:00',
  ],
  [
    'title' => 'Mejorar dashboard',
    'description' => 'Agregar gráficos de estadísticas recientes.',
    'status' => 'in_process',
    'priority' => 'medium',
    'category' => 'feature',
    'created_by' => 2,
    'assigned_to' => null,
    'created_at' => '2025-02-23 11:35:00',
  ],
  [
    'title' => 'Optimizar consultas SQL',
    'description' => 'Reducir tiempos de respuesta en listados.',
    'status' => 'in_process',
    'priority' => 'high',
    'category' => 'security',
    'created_by' => 3,
    'assigned_to' => 1,
    'created_at' => '2025-02-21 16:50:00',
  ],
  [
    'title' => 'Error en subida de archivos',
    'description' => 'Los adjuntos fallan al subir.',
    'status' => 'new',
    'priority' => 'critical',
    'category' => 'bug',
    'created_by' => 1,
    'assigned_to' => null,
    'created_at' => '2025-02-19 09:05:00',
  ],
  [
    'title' => 'Actualizar dependencias',
    'description' => 'Actualizar librerías obsoletas.',
    'status' => 'resolved',
    'priority' => 'low',
    'category' => 'maintenance',
    'created_by' => 2,
    'assigned_to' => 3,
    'created_at' => '2025-02-17 14:30:00',
  ],
  [
    'title' => 'Problema con permisos',
    'description' => 'Usuarios ven tickets que no les corresponden.',
    'status' => 'new',
    'priority' => 'critical',
    'category' => 'security',
    'created_by' => 3,
    'assigned_to' => 2,
    'created_at' => '2025-02-15 10:00:00',
  ],
  [
    'title' => 'Vista lenta de tickets',
    'description' => 'El listado tarda demasiado en cargar.',
    'status' => 'in_process',
    'priority' => 'medium',
    'category' => 'security',
    'created_by' => 1,
    'assigned_to' => null,
    'created_at' => '2025-02-25 09:45:00',
  ],
  [
    'title' => 'Revisión UX-UI',
    'description' => 'Mejorar la experiencia visual.',
    'status' => 'resolved',
    'priority' => 'medium',
    'category' => 'ux-ui',
    'created_by' => 2,
    'assigned_to' => 1,
    'created_at' => '2025-02-13 15:25:00',
  ],
  [
    'title' => 'Error en notificaciones',
    'description' => 'No llegan correos al crear tickets.',
    'status' => 'new',
    'priority' => 'high',
    'category' => 'feature',
    'created_by' => 3,
    'assigned_to' => 2,
    'created_at' => '2025-02-11 08:40:00',
  ],
  [
    'title' => 'Validación deficiente',
    'description' => 'Formularios aceptan datos inválidos.',
    'status' => 'new',
    'priority' => 'medium',
    'category' => 'frontend',
    'created_by' => 1,
    'assigned_to' => 3,
    'created_at' => '2025-02-09 13:55:00',
  ],
  [
    'title' => 'Error en logout',
    'description' => 'La sesión no se cierra correctamente.',
    'status' => 'new',
    'priority' => 'medium',
    'category' => 'bug',
    'created_by' => 2,
    'assigned_to' => 1,
    'created_at' => '2025-02-07 11:10:00',
  ],
  [
    'title' => 'Agregar búsqueda por texto',
    'description' => 'Permitir buscar tickets por título o descripción.',
    'status' => 'in_process',
    'priority' => 'low',
    'category' => 'feature',
    'created_by' => 1,
    'assigned_to' => null,
    'created_at' => '2025-02-05 16:20:00',
  ],
  [
    'title' => 'Problema con sesiones expiradas',
    'description' => 'Sesiones activas expiran antes de tiempo.',
    'status' => 'new',
    'priority' => 'high',
    'category' => 'security',
    'created_by' => 3,
    'assigned_to' => 2,
    'created_at' => '2025-02-03 09:30:00',
  ],
  [
    'title' => 'Corrección de estilos en móvil',
    'description' => 'La vista móvil se rompe en pantallas pequeñas.',
    'status' => 'in_process',
    'priority' => 'medium',
    'category' => 'ux-ui',
    'created_by' => 2,
    'assigned_to' => 3,
    'created_at' => '2025-02-01 14:45:00',
  ],
  [
    'title' => 'Error al editar tickets',
    'description' => 'Los cambios no se guardan correctamente.',
    'status' => 'new',
    'priority' => 'high',
    'category' => 'bug',
    'created_by' => 1,
    'assigned_to' => null,
    'created_at' => '2025-01-30 10:15:00',
  ],
  [
    'title' => 'Optimizar carga inicial',
    'description' => 'Reducir el tiempo de carga del dashboard.',
    'status' => 'in_process',
    'priority' => 'medium',
    'category' => 'security',
    'created_by' => 3,
    'assigned_to' => 1,
    'created_at' => '2025-01-28 15:35:00',
  ],
  [
    'title' => 'Revisión de roles',
    'description' => 'Auditar permisos de cada rol.',
    'status' => 'resolved',
    'priority' => 'low',
    'category' => 'security',
    'created_by' => 2,
    'assigned_to' => 3,
    'created_at' => '2025-01-26 12:00:00',
  ],
  [
    'title' => 'Error en filtros combinados',
    'description' => 'Estado y prioridad no funcionan juntos.',
    'status' => 'new',
    'priority' => 'high',
    'category' => 'bug',
    'created_by' => 1,
    'assigned_to' => null,
    'created_at' => '2025-01-24 08:50:00',
  ],
  [
    'title' => 'Mejorar mensajes de error',
    'description' => 'Mensajes más claros para el usuario.',
    'status' => 'in_process',
    'priority' => 'low',
    'category' => 'ux-ui',
    'created_by' => 3,
    'assigned_to' => 2,
    'created_at' => '2025-01-22 16:05:00',
  ],
  [
    'title' => 'Limpieza de código legacy',
    'description' => 'Eliminar código no utilizado.',
    'status' => 'resolved',
    'priority' => 'low',
    'category' => 'maintenance',
    'created_by' => 1,
    'assigned_to' => 2,
    'created_at' => '2025-01-20 13:40:00',
  ],
  [
    'title' => 'Error al eliminar tickets',
    'description' => 'No se eliminan tickets desde la interfaz.',
    'status' => 'new',
    'priority' => 'high',
    'category' => 'bug',
    'created_by' => 3,
    'assigned_to' => 1,
    'created_at' => '2025-01-22 16:05:00',
  ],
  [
    'title' => 'Implementar paginación',
    'description' => 'Agregar paginación al listado de tickets.',
    'status' => 'in_process',
    'priority' => 'medium',
    'category' => 'feature',
    'created_by' => 1,
    'assigned_to' => null,
    'created_at' => '2025-01-20 13:40:00',
  ],
  [
    'title' => 'Problema con CSRF',
    'description' => 'Falta protección CSRF en formularios.',
    'status' => 'new',
    'priority' => 'critical',
    'category' => 'security',
    'created_by' => 2,
    'assigned_to' => 3,
    'created_at' => '2025-01-18 09:25:00',
  ],
  [
    'title' => 'Error en actualización de estado',
    'description' => 'El estado del ticket no se actualiza.',
    'status' => 'new',
    'priority' => 'high',
    'category' => 'bug',
    'created_by' => 1,
    'assigned_to' => 2,
    'created_at' => '2025-01-16 14:55:00',
  ],
  [
    'title' => 'Mejorar accesibilidad',
    'description' => 'Agregar soporte para lectores de pantalla.',
    'status' => 'in_process',
    'priority' => 'low',
    'category' => 'ux-ui',
    'created_by' => 3,
    'assigned_to' => null,
    'created_at' => '2025-01-14 10:30:00',
  ],
  [
    'title' => 'Optimizar índices DB',
    'description' => 'Crear índices para mejorar consultas.',
    'status' => 'resolved',
    'priority' => 'medium',
    'category' => 'security',
    'created_by' => 2,
    'assigned_to' => 1,
    'created_at' => '2025-01-12 16:10:00',
  ],
  [
    'title' => 'Error en refresh automático',
    'description' => 'El listado no se refresca solo.',
    'status' => 'new',
    'priority' => 'medium',
    'category' => 'frontend',
    'created_by' => 1,
    'assigned_to' => null,
    'created_at' => '2025-01-10 11:20:00',
  ],
  [
    'title' => 'Auditoría de acciones',
    'description' => 'Registrar acciones de usuarios.',
    'status' => 'in_process',
    'priority' => 'low',
    'category' => 'feature',
    'created_by' => 2,
    'assigned_to' => 3,
    'created_at' => '2025-01-08 15:00:00',
  ],
  [
    'title' => 'Error en notificaciones push',
    'description' => 'Las notificaciones push no funcionan.',
    'status' => 'new',
    'priority' => 'high',
    'category' => 'feature',
    'created_by' => 3,
    'assigned_to' => 2,
    'created_at' => '2025-01-06 09:45:00',
  ],
  [
    'title' => 'Refactor de controlador',
    'description' => 'Simplificar lógica del controlador de tickets.',
    'status' => 'resolved',
    'priority' => 'low',
    'category' => 'maintenance',
    'created_by' => 1,
    'assigned_to' => 2,
    'created_at' => '2025-01-04 13:35:00',
  ],
  [
    'title' => 'Error en cambio de contraseña',
    'description' => 'Los usuarios no pueden cambiar su contraseña.',
    'status' => 'new',
    'priority' => 'high',
    'category' => 'bug',
    'created_by' => 2,
    'assigned_to' => 1,
    'created_at' => '2025-01-02 08:10:00',
  ],
  [
    'title' => 'Implementar historial de tickets',
    'description' => 'Mostrar historial de cambios del ticket.',
    'status' => 'in_process',
    'priority' => 'medium',
    'category' => 'feature',
    'created_by' => 1,
    'assigned_to' => null,
    'created_at' => '2024-12-30 17:50:00',
  ],
  [
    'title' => 'Problema con timezone',
    'description' => 'Las fechas no respetan la zona horaria.',
    'status' => 'new',
    'priority' => 'medium',
    'category' => 'bug',
    'created_by' => 3,
    'assigned_to' => 2,
    'created_at' => '2024-12-28 12:15:00',
  ],
  [
    'title' => 'Mejorar seguridad de sesión',
    'description' => 'Regenerar sesión tras login.',
    'status' => 'resolved',
    'priority' => 'high',
    'category' => 'security',
    'created_by' => 1,
    'assigned_to' => 3,
    'created_at' => '2024-12-26 09:00:00',
  ],
  [
    'title' => 'Error en ordenación por fecha',
    'description' => 'Los tickets no se ordenan correctamente.',
    'status' => 'new',
    'priority' => 'medium',
    'category' => 'bug',
    'created_by' => 2,
    'assigned_to' => null,
    'created_at' => '2024-12-24 16:40:00',
  ],
  [
    'title' => 'Optimizar uso de memoria',
    'description' => 'Reducir consumo de memoria en listados.',
    'status' => 'in_process',
    'priority' => 'low',
    'category' => 'security',
    'created_by' => 3,
    'assigned_to' => 1,
    'created_at' => '2024-12-22 10:05:00',
  ],
  [
    'title' => 'Agregar confirmaciones',
    'description' => 'Confirmar acciones destructivas.',
    'status' => 'resolved',
    'priority' => 'low',
    'category' => 'ux-ui',
    'created_by' => 1,
    'assigned_to' => 2,
    'created_at' => '2024-12-20 14:20:00',
  ],
  [
    'title' => 'Error en carga de avatares',
    'description' => 'Los avatares no se muestran.',
    'status' => 'new',
    'priority' => 'low',
    'category' => 'frontend',
    'created_by' => 2,
    'assigned_to' => null,
    'created_at' => '2024-12-18 08:30:00',
  ],
  [
    'title' => 'Revisión de validaciones backend',
    'description' => 'Faltan validaciones en endpoints.',
    'status' => 'in_process',
    'priority' => 'high',
    'category' => 'backend',
    'created_by' => 3,
    'assigned_to' => 2,
    'created_at' => '2024-12-16 11:45:00',
  ],
  [
    'title' => 'Documentar API interna',
    'description' => 'Crear documentación básica.',
    'status' => 'resolved',
    'priority' => 'low',
    'category' => 'feature',
    'created_by' => 1,
    'assigned_to' => 3,
    'created_at' => '2024-12-15 09:10:00',
  ],
];

$stmt = $pdo->prepare("
    INSERT OR IGNORE INTO 
    tickets (
              title, description,
              status, priority,
              category, created_by,
              assigned_to, created_at
            )
    VALUES (
            :title, :description,
            :status, :priority,
            :category, :created_by,
            :assigned_to, :created_at
            )
");

foreach ($tickets as $ticket) {
  $stmt->execute($ticket);
}

echo "Seed de tickets insertado correctamente.\n";
